services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticpin-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env


