package users
package adminusers

import (

















































































































}	})		"play":   playCount,		"dining": diningCount,		"events": eventCount,	return c.JSON(fiber.Map{	playCount, _ := config.GetDB().Collection("play_bookings").CountDocuments(ctx, bson.M{"user_email": u.Phone})	diningCount, _ := config.GetDB().Collection("dining_bookings").CountDocuments(ctx, bson.M{"user_email": u.Phone})	eventCount, _ := config.GetDB().Collection("bookings").CountDocuments(ctx, bson.M{"user_email": u.Phone})	}		return c.Status(404).JSON(fiber.Map{"error": "user not found"})	if err := config.GetDB().Collection("users").FindOne(ctx, bson.M{"_id": id}).Decode(&u); err != nil {	var u models.User	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	}		return c.Status(400).JSON(fiber.Map{"error": "invalid user id"})	if err != nil {	id, err := primitive.ObjectIDFromHex(c.Params("id"))func GetUserStats(c *fiber.Ctx) error {}	return c.JSON(allBookings)	}		allBookings = append(allBookings, rows...)		cursor.Close(ctx)		cursor.All(ctx, &rows)		var rows []Booking		}			continue		if err != nil {		cursor, err := config.GetDB().Collection(col).Find(ctx, bson.M{"user_email": u.Phone})	for _, col := range cols {	cols := []string{"bookings", "dining_bookings", "play_bookings"}	allBookings := []Booking{}	type Booking = map[string]interface{}	}		return c.Status(404).JSON(fiber.Map{"error": "user not found"})	if err := config.GetDB().Collection("users").FindOne(ctx, bson.M{"_id": id}).Decode(&u); err != nil {	var u models.User	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	}		return c.Status(400).JSON(fiber.Map{"error": "invalid user id"})	if err != nil {	id, err := primitive.ObjectIDFromHex(c.Params("id"))func GetUserBookings(c *fiber.Ctx) error {}	return c.JSON(fiber.Map{"message": "user deleted"})	}		return c.Status(500).JSON(fiber.Map{"error": err.Error()})	if _, err := config.GetDB().Collection("users").DeleteOne(ctx, bson.M{"_id": id}); err != nil {	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	}		return c.Status(400).JSON(fiber.Map{"error": "invalid user id"})	if err != nil {	id, err := primitive.ObjectIDFromHex(c.Params("id"))func DeleteUser(c *fiber.Ctx) error {}	return c.JSON(fiber.Map{"message": "user updated"})	}		return c.Status(500).JSON(fiber.Map{"error": err.Error()})	if err != nil {	_, err = config.GetDB().Collection("users").UpdateOne(ctx, bson.M{"_id": id}, bson.M{"$set": update})	}		update["phone"] = req.Phone	if req.Phone != "" {	}		update["name"] = req.Name	if req.Name != "" {	update := bson.M{}	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	}		return c.Status(400).JSON(fiber.Map{"error": "invalid request"})	if err := c.BodyParser(&req); err != nil {	}		Phone string `json:"phone"`		Name  string `json:"name"`	var req struct {	}		return c.Status(400).JSON(fiber.Map{"error": "invalid user id"})	if err != nil {	id, err := primitive.ObjectIDFromHex(c.Params("id"))func UpdateUser(c *fiber.Ctx) error {}	return c.JSON(u)	}		return c.Status(404).JSON(fiber.Map{"error": "user not found"})	if err := config.GetDB().Collection("users").FindOne(ctx, bson.M{"_id": id}).Decode(&u); err != nil {	var u models.User	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	}		return c.Status(400).JSON(fiber.Map{"error": "invalid user id"})	if err != nil {	id, err := primitive.ObjectIDFromHex(c.Params("id"))func GetUser(c *fiber.Ctx) error {)	"go.mongodb.org/mongo-driver/bson/primitive"	"go.mongodb.org/mongo-driver/bson"	"github.com/gofiber/fiber/v2"	"ticpin-backend/models"	"ticpin-backend/config"	"time"	"context"